<?php

namespace App;

use App\ORM\SharedLocalizationAttributes;
use Illuminate\Database\Eloquent\Model;

class Group extends Model
{
    protected $guarded = [];

    use SharedLocalizationAttributes;

    public function posts()
    {
        return $this->morphMany(Post::class,'poster');
    }
    public function getRouteKeyName()
    {
        return 'slug'; // TODO: Change the autogenerated stub
    }


    public function is($slug = 'co-related',$isSystem = true)
    {
        return $this->slug  ==  'application-' . $slug;

    }
    private static function _getSystemGroup($slug = 'events')
    {
        return Group::where([[
            'is_system_group' , true],
            ['slug' , 'application-' . $slug]
        ])->first();
    }

    public static function getSystemLatestNewsGroup()
    {
        return self::_getSystemGroup('latest-news');
    }
    public static function getSystemEventGroup()
    {
        return self::_getSystemGroup('events');
    }

    public static function getSystemBannerGroup()
    {
        return self::_getSystemGroup('banner');
    }

    public static function getSystemAdvertisementGroup()
    {
        return self::_getSystemGroup('advertisements');
    }

    public static function getSystemInformationGroup()
    {
        return self::_getSystemGroup('information');
    }

    public static function getSystemVisionGroup()
    {
        return self::_getSystemGroup('vission');
    }
    public static function getSystemGoalsGroup()
    {
        return self::_getSystemGroup('objectives');
    }
    public static function getSystemEServicesGroup()
    {
        return self::_getSystemGroup('e-services');
    }

    public static function getSystemCoRelatedGroup()
    {
        return self::_getSystemGroup('co-related');
    }
}
